name: "Release"
on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.release.target_commitish }} == 'master'
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v5
        with:
          go-version: "1.26.0"

      - name: Set tag in environment
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV # extracts the tag name from refs/tags/v1.2.3

      - name: "Build image"
        run: make docker-build TAG=$RELEASE_VERSION

      - name: "Docker login to Quay.io"
        env:
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
        run: docker login -u $QUAY_USERNAME -p $QUAY_PASSWORD quay.io

      - name: "Push image"
        run: make docker-push TAG=$RELEASE_VERSION
